#!/usr/bin/python

import errno
import json
import os
import signal
import subprocess
import sys
import time

try:
    string_types = (str, unicode)
except NameError:
    string_types = (str,)

try:
    _basestring = basestring
except NameError:
    _basestring = str

try:
    _fspath = os.fspath
except AttributeError:
    def _fspath(path):
        if hasattr(path, '__fspath__'):
            return path.__fspath__()
        if isinstance(path, _basestring):
            return path
        return str(path)

try:
    _replace = os.replace
except AttributeError:
    if os.name == 'posix':
        _replace = os.rename
    else:
        def _replace(src, dst):
            try:
                os.remove(dst)
            except OSError:
                pass
            os.rename(src, dst)

OVERRIDE_SOURCE = '/mnt/lg/cmn_data/sdp/sdx/detailconfig.json'
OVERRIDE_DESTINATION = '/tmp/ad_killer-detailconfig.json'
BLOCK_STUB = '/tmp/ad_killer-blocked'
BLOCK_STATE = '/tmp/ad_killer-blocked-paths'
LEGACY_WATCHDOG_PID = '/tmp/ad_killer-watchdog.pid'
DISABLE_MARKER = '/var/lib/webosbrew/ad-killer.disabled'

REQUIRED_SHELVES = {'HOME_SH_APPS', 'HOME_SH_HOMEDASHBOARD'}
PROMOTIONAL_SHELVES = {
    'HOME_SH_AMAZONPRIME',
    'HOME_SH_BROWSER',
    'HOME_SH_CONTENTPROMOTION',
    'HOME_SH_CONTENT_PREVIEW',
    'HOME_SH_EDITORSPICK',
    'HOME_SH_GAME',
    'HOME_SH_INLINEADBANNER',
    'HOME_SH_LGCHANNELS_GB',
    'HOME_SH_LGCHANNELS_GIP',
    'HOME_SH_LGRECOMMEND_1',
    'HOME_SH_LGRECOMMEND_2',
    'HOME_SH_LIFEONSCREEN',
    'HOME_SH_LIVETV',
    'HOME_SH_RECOMMENDED',
    'HOME_SH_SHOPPING_EU',
    'HOME_SH_SPORTSALERT',
}

ADS_TELEMETRY_EXECUTABLES = {
    '/usr/sbin/acr2',
    '/usr/sbin/admanager',
    '/usr/sbin/nudge',
    '/usr/sbin/rdxd',
    '/usr/sbin/sportsalarm',
    '/usr/sbin/uploadd',
}
PRIVACY_BLOAT_EXECUTABLES = {
    '/usr/sbin/amazon-alexa-adapter',
    '/usr/sbin/amazon-alexa-vsk',
    '/usr/sbin/iot-client',
    '/usr/sbin/lg.thinqai.adapter',
    '/usr/sbin/mqtt-client',
    '/usr/sbin/musicrecognition',
    '/usr/sbin/nlpmanager',
    '/usr/sbin/performer',
    '/usr/sbin/voiceconductor',
    '/usr/sbin/voiceinput',
    '/var/palm/jail/amazon.alexa.adapter/usr/sbin/amazon-alexa-adapter',
    '/var/palm/jail/amazon.alexa.adapter/usr/sbin/amazon-alexa-vsk',
    '/var/palm/jail/com.webos.service.voice.performer/usr/sbin/performer',
    '/var/palm/jail/lg.thinqai.adapter/usr/sbin/lg.thinqai.adapter',
}
ADS_SYSTEMD_UNITS = {
    'nudge.service',
    'uploadd.service',
}
PRIVACY_SYSTEMD_UNITS = {
    'musicrecognition.service',
    'voiceconductor.service',
    'voiceinput.service',
}
SDX_EXECUTABLE = '/usr/sbin/sdx'
HOME_EXECUTABLE = '/usr/bin/com.webos.app.home'


def log(message):
    sys.stdout.write('ad_killer: {0}\n'.format(message))
    sys.stdout.flush()


def run(command, check=True):
    devnull = open(os.devnull, 'wb')
    try:
        returncode = subprocess.call(command, stdout=devnull, stderr=devnull)
    finally:
        devnull.close()
    if check and returncode != 0:
        raise subprocess.CalledProcessError(returncode, command)
    return returncode


def selected_executables(profile):
    if profile == 'ads':
        return ADS_TELEMETRY_EXECUTABLES
    return ADS_TELEMETRY_EXECUTABLES | PRIVACY_BLOAT_EXECUTABLES


def selected_units(profile):
    if profile == 'ads':
        return ADS_SYSTEMD_UNITS
    return ADS_SYSTEMD_UNITS | PRIVACY_SYSTEMD_UNITS


def shelf_lists(data):
    if not isinstance(data, dict) or not isinstance(data.get('smartConfig'), list):
        raise ValueError('invalid smartConfig structure')
    for smart_config in data['smartConfig']:
        if not isinstance(smart_config, dict):
            continue
        ai_home = smart_config.get('ai_home')
        if not isinstance(ai_home, dict):
            continue
        shelves = ai_home.get('ai_home_info')
        if isinstance(shelves, list):
            yield ai_home, shelves


def clean_shelves(source, destination):
    source = _fspath(source)
    destination = _fspath(destination)
    with open(source) as source_file:
        data = json.load(source_file)

    removed = set()
    retained_ids = set()
    found_shelves = False
    for ai_home, shelves in shelf_lists(data):
        found_shelves = True
        filtered = []
        for shelf in shelves:
            shelf_id = shelf.get('shelfId') if isinstance(shelf, dict) else None
            if shelf_id in PROMOTIONAL_SHELVES:
                removed.add(shelf_id)
                continue
            filtered.append(shelf)
            if isinstance(shelf_id, string_types):
                retained_ids.add(shelf_id)
        ai_home['ai_home_info'] = filtered

    if not found_shelves:
        raise ValueError('no ai_home_info shelves found')
    missing = REQUIRED_SHELVES - retained_ids
    if missing:
        raise ValueError('required shelves missing: {0}'.format(sorted(missing)))

    temporary = destination + '.tmp'
    with open(temporary, 'w') as destination_file:
        json.dump(data, destination_file, separators=(',', ':'))
        destination_file.flush()
        os.fsync(destination_file.fileno())
    with open(temporary) as validation_file:
        validated = json.load(validation_file)
    list(shelf_lists(validated))
    _replace(temporary, destination)
    return removed


def install_shelf_override(dry_run=False):
    if not os.path.isfile(OVERRIDE_SOURCE):
        raise IOError(errno.ENOENT, 'missing webOS shelf configuration: ' + OVERRIDE_SOURCE)
    if dry_run:
        destination = '/tmp/ad_killer-dry-run.json'
        removed = clean_shelves(OVERRIDE_SOURCE, destination)
        try:
            os.unlink(destination)
        except (IOError, OSError):
            pass
        return removed

    run(['umount', OVERRIDE_SOURCE], check=False)
    removed = clean_shelves(OVERRIDE_SOURCE, OVERRIDE_DESTINATION)
    run(['mount', '--bind', OVERRIDE_DESTINATION, OVERRIDE_SOURCE])
    return removed


def exact_process_path(pid, proc_root='/proc'):
    try:
        path = os.readlink(os.path.join(proc_root, str(pid), 'exe'))
    except (EnvironmentError, AttributeError):
        return None
    suffix = ' (deleted)'
    return path[:-len(suffix)] if path.endswith(suffix) else path


def matching_pids(executables, proc_root='/proc'):
    matches = []
    for entry in os.listdir(proc_root):
        if not entry.isdigit():
            continue
        pid = int(entry)
        if pid != os.getpid() and exact_process_path(pid, proc_root) in executables:
            matches.append(pid)
    return sorted(matches)


def terminate_processes(executables, dry_run=False):
    pids = matching_pids(executables)
    if dry_run:
        return pids
    for pid in pids:
        try:
            os.kill(pid, signal.SIGTERM)
        except (EnvironmentError, OSError):
            pass
    return pids


def kill_surviving_pids(pids):
    killed = []
    for pid in pids:
        if not os.path.exists('/proc/{0}'.format(pid)):
            continue
        try:
            os.kill(pid, signal.SIGKILL)
            killed.append(pid)
        except (EnvironmentError, OSError):
            pass
    return killed


def stop_units(units, dry_run=False):
    if dry_run:
        return
    for unit in sorted(units):
        run(['systemctl', '--no-block', 'stop', unit], check=False)


def start_units(units):
    for unit in sorted(units):
        run(['systemctl', '--no-block', 'start', unit], check=False)


def previous_block_paths():
    try:
        with open(BLOCK_STATE) as state_file:
            return [line.strip() for line in state_file if line.strip()]
    except (IOError, OSError):
        return []


def remove_process_blocks():
    for path in previous_block_paths():
        run(['umount', path], check=False)
    try:
        os.unlink(BLOCK_STATE)
    except (IOError, OSError):
        pass


def install_process_blocks(executables, dry_run=False):
    paths = [path for path in sorted(executables) if os.path.isfile(path)]
    if dry_run:
        return paths

    remove_process_blocks()
    with open(BLOCK_STUB, 'w') as stub_file:
        stub_file.write('#!/bin/sh\nexit 0\n')
    os.chmod(BLOCK_STUB, 0o755)
    for path in paths:
        run(['mount', '--bind', BLOCK_STUB, path])
    with open(BLOCK_STATE, 'w') as state_file:
        state_file.write('\n'.join(paths) + '\n')
    return paths


def stop_legacy_watchdog():
    try:
        with open(LEGACY_WATCHDOG_PID) as pid_file:
            pid = int(pid_file.read().strip())
        with open('/proc/{0}/cmdline'.format(pid), 'rb') as command_file:
            command = command_file.read().replace(b'\0', b' ')
        if b'ad_killer' in command and b'--watch' in command:
            os.kill(pid, signal.SIGTERM)
    except (EnvironmentError, OSError, ValueError):
        pass
    try:
        os.unlink(LEGACY_WATCHDOG_PID)
    except (IOError, OSError):
        pass


def rollback():
    stop_legacy_watchdog()
    remove_process_blocks()
    run(['umount', OVERRIDE_SOURCE], check=False)
    start_units(ADS_SYSTEMD_UNITS | PRIVACY_SYSTEMD_UNITS)

class Namespace(object):
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def __repr__(self):
        keys = sorted(self.__dict__.keys())
        items = ['{0}={1!r}'.format(k, getattr(self, k)) for k in keys]
        return 'Namespace({0})'.format(', '.join(items))


def parse_args(args=None):
    if args is None:
        args = sys.argv[1:]

    default_profile = os.environ.get('AD_KILLER_PROFILE', 'privacy')
    if default_profile not in ('ads', 'privacy'):
        default_profile = 'privacy'

    opts = Namespace(
        disable=False,
        dry_run=False,
        enable=False,
        refresh_home=False,
        profile=default_profile,
    )

    idx = 0
    while idx < len(args):
        arg = args[idx]
        if arg in ('-h', '--help'):
            sys.stdout.write(
                'usage: ad_killer [-h] [--disable] [--dry-run] [--enable] [--refresh-home]\n'
                '                 [--profile {ads,privacy}]\n\n'
                'Remove LG webOS ads and optional privacy bloat\n\n'
                'optional arguments:\n'
                '  -h, --help            show this help message and exit\n'
                '  --disable\n'
                '  --dry-run\n'
                '  --enable\n'
                '  --refresh-home\n'
                '  --profile {ads,privacy}\n'
            )
            sys.exit(0)
        elif arg == '--disable':
            opts.disable = True
        elif arg == '--dry-run':
            opts.dry_run = True
        elif arg == '--enable':
            opts.enable = True
        elif arg == '--refresh-home':
            opts.refresh_home = True
        elif arg == '--profile':
            idx += 1
            if idx >= len(args) or args[idx] not in ('ads', 'privacy'):
                sys.stderr.write('ad_killer: error: argument --profile: invalid choice (choose from "ads", "privacy")\n')
                sys.exit(2)
            opts.profile = args[idx]
        elif arg.startswith('--profile='):
            val = arg.split('=', 1)[1]
            if val not in ('ads', 'privacy'):
                sys.stderr.write('ad_killer: error: argument --profile: invalid choice (choose from "ads", "privacy")\n')
                sys.exit(2)
            opts.profile = val
        else:
            sys.stderr.write('ad_killer: error: unrecognized argument: {0}\n'.format(arg))
            sys.exit(2)
        idx += 1

    return opts



def main():
    args = parse_args()
    if args.disable:
        rollback()
        with open(DISABLE_MARKER, 'w') as marker:
            marker.write('disabled\n')
        log('disabled and rolled back; reboot is not required')
        return
    if args.enable:
        try:
            os.unlink(DISABLE_MARKER)
        except (IOError, OSError):
            pass
    elif os.path.exists(DISABLE_MARKER):
        log('disabled by {0}'.format(DISABLE_MARKER))
        return

    stop_legacy_watchdog()
    removed_shelves = install_shelf_override(dry_run=args.dry_run)
    executables = selected_executables(args.profile)
    units = selected_units(args.profile)
    stop_units(units, dry_run=args.dry_run)
    if not args.dry_run:
        remove_process_blocks()
    stopped_pids = terminate_processes(executables | {SDX_EXECUTABLE}, dry_run=args.dry_run)
    if stopped_pids and not args.dry_run:
        time.sleep(0.5)
    blocked_paths = install_process_blocks(executables, dry_run=args.dry_run)
    if args.dry_run:
        killed_pids = []
    else:
        surviving_pids = matching_pids(executables)
        killed_pids = kill_surviving_pids(sorted(set(stopped_pids + surviving_pids)))
    home_pids = []
    if args.refresh_home:
        home_pids = terminate_processes({HOME_EXECUTABLE}, dry_run=args.dry_run)

    log('profile={0}'.format(args.profile))
    log('removed shelves={0}'.format(','.join(sorted(removed_shelves)) or 'none'))
    log('blocked executables={0}'.format(','.join(blocked_paths) or 'none'))
    log('matched process pids={0}'.format(','.join(map(str, stopped_pids)) or 'none'))
    log('force-stopped pids={0}'.format(','.join(map(str, killed_pids)) or 'none'))
    if args.refresh_home:
        log('home pids to refresh={0}'.format(','.join(map(str, home_pids)) or 'none'))


if __name__ == '__main__':
    main()
